version: '3.7'

volumes:
  postgres:

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_DB: "DoramaSet"
      POSTGRES_USER: karine
      POSTGRES_PASSWORD: 12346
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/data
      - ./docker:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5431:5432"
    networks:
      - my_persistent_network

  mongo:
    container_name: mongo_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: karine
      MONGO_INITDB_ROOT_PASSWORD: 12346
      MONGO_INITDB_DATABASE: "DoramaSet"
    volumes:
      - ./data:/csv:rx
      - ./init/mongo/:/docker-entrypoint-initdb.d/
    ports:
      - "27018:27017"
    networks:
      - my_persistent_network

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"

networks:
  my_persistent_network:
    driver: bridge