version: '3.7'

volumes:
  postgres:

services:
  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_DB: "DoramaSet"
      POSTGRES_USER: karine
      POSTGRES_PASSWORD: 12346
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/data
      - ./docker:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - my_persistent_network

  mongo:
    container_name: mongo_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: karine
      MONGO_INITDB_ROOT_PASSWORD: 12346
      MONGO_INITDB_DATABASE: "DoramaSet"
    volumes:
      - ./data:/csv
      - ./docker/mgdata:/data/db
      - ./init/mongo/:/docker-entrypoint-initdb.d/
    ports:
      - "27017:27017"
    networks:
      - my_persistent_network

#  zookeeper:
#    hostname: myzookeeper
#    container_name: zookeeper
#    image: 'bitnami/zookeeper:3.7.0'
#    restart: on-failure
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#    networks:
#      - my_persistent_network
#
#  registry:
#    hostname: myregistry
#    container_name: registry
#    image: 'apache/nifi-registry:1.15.0'
#    restart: on-failure
#    ports:
#      - "18080:18080"
#    environment:
#      - LOG_LEVEL=INFO
#      - NIFI_REGISTRY_DB_DIR=/opt/nifi-registry/nifi-registry-current/database
#      - NIFI_REGISTRY_FLOW_PROVIDER=file
#      - NIFI_REGISTRY_FLOW_STORAGE_DIR=/opt/nifi-registry/nifi-registry-current/flow_storage
#    volumes:
#      - ./docker/nifi_registry/database:/opt/nifi-registry/nifi-registry-current/database
#      - ./docker/nifi_registry/flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
#    networks:
#      - my_persistent_network
#
#  nifi:
#    hostname: mynifi
#    container_name: nifi
#    image: 'apache/nifi:1.14.0'
#    restart: on-failure
#    ports:
#      - '8091:8080'
#    environment:
#      - NIFI_WEB_HTTP_PORT=8080
#      - NIFI_CLUSTER_IS_NODE=true
#      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
#      - NIFI_ZK_CONNECT_STRING=myzookeeper:2181
#      - NIFI_ELECTION_MAX_WAIT=30 sec
#      - NIFI_SENSITIVE_PROPS_KEY='12345678901234567890A'
#    healthcheck:
#      test: "${DOCKER_HEALTHCHECK_TEST:-curl localhost:8091/nifi/}"
#      interval: "60s"
#      timeout: "3s"
#      start_period: "5s"
#      retries: 5
#    volumes:
#      - ./docker/nifi/database_repository:/opt/nifi/nifi-current/database_repository
#      - ./docker/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
#      - ./docker/nifi/content_repository:/opt/nifi/nifi-current/content_repository
#      - ./docker/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
#      - ./docker/nifi/state:/opt/nifi/nifi-current/state
#      - ./docker/nifi/logs:/opt/nifi/nifi-current/logs
#      - ./docker/nifi/jks:/opt/nifi/nifi-current/jks
#      - ./docker/nifi/in_file:/opt/nifi/nifi-current/in_file
#      - ./data:/data
#    networks:
#      - my_persistent_network

networks:
  my_persistent_network:
    driver: bridge