DB:
  Host: "localhost"
  Username: "karine"
  Password: "12346"
  DBName: "DoramaSet"
  SSLMode: "disable"
  Port: 5432

App:
  SecretKey: "qwerty"
  EveryDayPoint: 5
  EveryYearPoint: 10
  LongNoLoginPoint: 50
  LongNoLoginHours: 4400.0
  LoginLen: 5
  PasswordLen: 8
  TokenExpirationHours: 700

Logger:
  FileName: "log.txt"
  Level: 6