DB:
  Host: "localhost"
  Username: "karine"
  Password: "12346"
  DBName: "DoramaSet"
  SSLMode: "disable"
  Port: 5431
  Type: postgres

App:
  SecretKey: "qwerty"
  EveryDayPoint: 5
  EveryYearPoint: 10
  LongNoLoginPoint: 50
  LongNoLoginHours: 4400.0
  LoginLen: 5
  PasswordLen: 8
  TokenExpirationHours: 700

Logger:
  FileName: "log.txt"
  Level: debug

Server:
  Port: "8000"
  Mode: debug

OpenTelemetry:
  Endpoint: "http://localhost:14268/api/traces"
  ServiceName: main
  Ratio: 1.0