DB:
  Host: {{ .Host }}
  Username: "karine"
  Password: "12346"
  DBName: "DoramaSet"
  SSLMode: "disable"
  Port: {{ .Port }}
  Type: postgres

App:
  SecretKey: "qwerty"
  EveryDayPoint: 5
  EveryYearPoint: 10
  LongNoLoginPoint: 50
  LongNoLoginHours: 4400.0
  LoginLen: 5
  PasswordLen: 8
  TokenExpirationHours: 700

Logger:
  FileName: "e2e.log"
  Level: debug

Server:
  Port: "8080"
  Mode: debug